### ISSUE TITLE
session problem

### ISSUE THREAD

**Issue by jorgejavier** [hwz/chirp#7]
Hi, first of all great tutorial!! I follow it but when my user logs in and I f5 the page it has to log again. Any suggestions? Thanks in advance.

**Comment by piq9117** [comment]
I was just wondering about this. Did you figure it out?

**Comment by jorgejavier** [comment]
Yes I did, the problem was that I wasn't persisting the session, each time you refresh you lost all session data, cause it is javascript, so you need to use something like https://github.com/grevory/angular-local-storage to save it.
